sudo: required
language: python
python:
  - "2.7"

install:
- pip install -r requirements.txt

script:
- python -m flake8 --max-line-length=120 tester_gae
- python -m pylint tester_gae
- python -m coverage run tests/run_tests.py
- python -m coveralls
- python -m coverage report --skip-covered
