name: test.helper.gae tests

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        flake8 --count --show-source --statistics --max-line-length=120 --exclude=libs tester_gae
    - name: Lint with pylint
      run: |
        python -m pylint --disable=relative-import tester_gae
    - name: Test with pytest
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        pytest --cov=source --cov-report xml --cov-report term:skip-covered --durations=5 tests
        python-codacy-coverage -r coverage.xml
